### PR TITLE
Set variables as !default

### PR DESCRIPTION
**Pull request by jrschumacher**
> You can assign to variables if they aren’t already assigned by adding the !default flag to the end of the value. This means that if the variable has already been assigned to, it won’t be re-assigned, but if it doesn’t have a value yet, it will be given one.

### CODE REVIEW

**Comment by gordalina** [comment]
Major plus to this! ping @zavoloklom

**Comment by cbaur** [comment]
+1 here!

**Comment by Ollo** [comment]
:+1:

**Comment by tomasruud** [comment]
Please merge this. :smile_cat:

**Comment by gitawego** [comment]
+1

**Comment by zavoloklom** [comment]
Fixed in [2.0 release](https://github.com/zavoloklom/material-design-iconic-font/releases)

**Pull request closed without merging**
