### PR TITLE
Fix angular material compatability

### PR DESCRIPTION
**Pull request by leonzinger**
change the md to mdi

### CODE REVIEW

**Comment by gustavohenke** [comment]
:+1: 
I think compatibility with Angular Material is a must, as it's probably the best known and most used material implementation.

**Comment by leonzinger** [comment]
@davidkpiano You were right, locally it worked with the css version changed. In production, the path is broken.
Font awesome uses different technique to overcome this problem just by loading the fonts from the scss file like this:

     $fa-font-path: "/bower_components/font-awesome/fonts";

    @import 'font-awesome/scss/font-awesome';

So adding the !default to the variables is a must :)

**Comment by leonzinger** [comment]
@davidkpiano added another commit to fix https://github.com/zavoloklom/material-design-iconic-font/issues/13 issue

**Comment by leonzinger** [comment]
So anyone using Yeoman grunt builds, this is what i have done:

in your main scss file add the following lines of code:

    $md-css-prefix: mdi;
    $md-font-path: "/bower_components/material-design-iconic-font/fonts";

    @import 'material-design-iconic-font/scss/material-design-iconic-font';

in Gruntfile.js under wiredep.exclude add this:

    /material-design-iconic-font.css/

**Comment by eckyputrady** [comment]
I have compatibility problem in my project and I solved it using `mdi` too. I really hope this PR merged soon.

**Comment by scarletsky** [comment]
hopes to merge +1

**Comment by zavoloklom** [comment]
Fixed in [2.0 release](https://github.com/zavoloklom/material-design-iconic-font/releases)

**Pull request closed without merging**
